import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  newArrFive,
  image14,
  image15,
  image16,
  image17,
  image18,
  image19,
  image20,
  image21,
  image22,
  image23,
  image24,
  image25,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "MIXCART Multicolor Sky Moon Star Master Dream Usb Led Night Light pack of 1",
    price: "330.00",
    color: "Multi",
    badge: true,
    des: "Feature-this night light can use the usb or battery power supply it can control rotation and make lamp luminous or colorful light. So beautiful best gift for your kids they will be a good sleep at night for decorating wedding, birthday, parties. Great for romantic night lamp and decoration light use. Best for home, bedroom, children rooms. Very romantic night, full of sincere gift. Power by 4 x aaa battery not included or usb cable. Energy power saving and environmental friendly.",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Jaiman Toys LEGO Technic Ferrari Daytona Sp3 42143 Building Kit (3,778 Pieces), Multi Color",
    price: "48990.00",
    color: "Red",
    badge: true,
    des: "From the LEGO Technic Ultimate Car Concept series-The 4th addition to this series of supercar builds: a range of collectible models inspired by some of the world's most luxurious vehicles",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Rubela Kitchen Set Cooking Toy with Briefcase and Accessories, 26 PCS. Kitchen Playing Set",
    price: "399.00",
    color: "Mixed",
    badge: true,
    des: "Rubela Presents Kitchen Set is all that the children need to cook in their own Pretend Play Kitchen Set. This Play Set gets the kids to involve themselves in playful activities that are highly beneficial to them and also Super Fun. It is the best Cooking Companion for all-day fun play. Children can pretend cooking with utensils which encourages their fine motor skills, role-playing, imaginative play and introduces the kids to daily household kitchen chores. Best Cooking Pretend Play Set for Active Role-Play and Super Fun-Filled Hours. This is the ultimate gift for every little boy or girl! Great for birthdays, name days and Christmas gift-giving, it will surely put an ear-to-ear smile on your kid’s face.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Zyamalox Little Toys Multicolor Plastic Electric Water Circulation with Music Light Go Fishing Game Board Play Set Toy - Pack of 21",
    price: "₹1299.00",
    color: "Multi",
    badge: true,
    des: "Promotes hand and eye coordination. Creates a fun and interactive fishing experience for child. Add water to fishing board and activate the buttons, water will go into circular motion. Accompanied music and lighting. Water scoop for fishing. Fishing rod rotates 360 degrees. Promotes bonding time with child when playing in 2 persons mode. Beautiful waterproof stickers. Multiple accessories.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: newArrOne,
    productName: "Party Wear",
    price: "440.00",
    color: "Multi",
    badge: true,
    des:"Party Dress: Dresses designed for parties and special events, usually featuring embellishments, lace, or satin materials."
    ,
  },
  {
    _id: 1002,
    img: newArrTwo,
    productName: "Comfort Wear",
    price: "250.00",
    color: "Red",
    badge: true,
    des:"Perfect for everyday wear, our dresses are comfortable and designed with the latest fashion trends in mind.",
  },  
  {
    _id: 1003,
    img: newArrThree,
    productName: "Dresses & Frocks",
    price: "780.00",
    color: "Mixed",
    badge: true,
    des:"A lovely Frock dress in vibrant colours for your little girl. An adorable classic bow making a chic statement and stripes creating there own magic. Perfect dress to adorn for that day out.."
    ,
  },
  {
    _id: 1004,
    img: newArrFour,
    productName: "TENDSY",
    price: "499.00",
    color: "Black",
    badge: true,
    des:"Stretchable & Shrinkage Resistant Fabric: The Baby Socks are made with cotton fabric keeping in mind the ultra-sensitive skin of babies in mind. These are breathable, sweat-resistant, and odorless."
    ,
  },
  {
    _id: 1005,
    img:newArrFive,
    productName: "KIDIS LAND Stylish Printed Boys Winter Wear Kids Clothing Sets",
    price: "499.00",
    color: "Mixed",
    badge: true,
    des:"Kidis Land Kids Unisex Tees Short Sets are a great choice for parents who want to make sure their children are comfortable wearing quality clothes. These Sets are perfect for children of all ages. They are made of premium quality cotton and polyester material and are vibrant, safe, and durable. Whether you are looking for your kid to wear something for school or for a special occasion, we have you covered in everything. We have a great collection for little champs."
    ,
  },
  {
    _id: 1006,
    img: bestSellerOne,
    productName:"DASH Victor Tricycle for Kids, Baby Cycle, Kids Cycle, Tricycle for Kids for 2 Years to 5 Years with Under Seat Storage, Light and Music",
    price: "2649.00",
    color: "Red",
    badge: false,
    des: "Dash, an ISO 9001:2008 manufacturing organization, is India’s leading manufacturer of Baby Products like Baby Tricycles, Walkers, Cars, Scooters, Swings, Rockers etc. It lays utmost importance to the Quality right from the procurement of raw materials to the manufacturing of the final product. The company’s aim is to give world class products at competitive prices. Trendy Design This tricycle is one of the best products created by NHR with some high and good quality raw materials. This stylish and modern age scooter with sports bike looks is an ideal companion for your toddlers. An engine like structure installed under the seat gives a classy look. Back view mirrors reflect the images to let your kid feel like a real bike ride. Comfortable Ride Comfort and safety both are the elements we search for, in needed things especially if it is for the child. Such comfort your kids can experience while riding this cycle. It has a wide seat with a backrest to support their sensitive back. Twirled design on wheels gives a stable ride.",
  },
  {
    _id: 1007,
    img: bestSellerTwo,
    productName: "Jaspo Multicolor Outdoor Sports Combo Set",
    price: "1889.00",
    // color: "Mixed",
    badge: true,
    des: "Jaspo beach set comes with three combo up to 8 years, 8-12 years and 12 yrs and above. Beach set is best played on outdoor surfaces such as grass and sand. Better to play beach games. Suitable for kids, boys and girls. Encourages to playing indoor and outdoor sports. Beach set is applicable to play anywhere such as lawn, camping area, beach or backyard.",
  },
  {
    _id: 1008,
    img: bestSellerThree,
    productName: "Tway Stylish Kids Sports shoes Black for Boys Casual Running Walking and Hikking shoes",
    price: "979.00",
    color: "Mixed",
    badge: false,
    des: "Lightweight Daily wear shoes for Kids, Make your steps comfortable and Enter a new world of comfort with this pair of Sports Shoe, easy to wash at home, set your own fashion statement that make you stand out from the crowd, built to last, to provide comfort to the feet, Comfort Sole & Flexible Walk, you are buying a trust of best quality shoes in best low price with a friendly customer service.",
  },
  {
    _id: 1009,
    img: bestSellerFour,
    productName: "Vector X Street Mania Hand Stitched Football (Size-5)",
    price: "399.00",
    color: "Black with white",
    badge: true,
    des: "Outer Material : Rubber,Size :5,Diameter : 68cms,Weight : 420-425grams, Hand Stitched Football,Pin is included in the package"
  },
  {
    _id: 1010,
    img: spfOne,
    productName: "MIXCART Multicolor Sky Moon Star Master Dream Usb Led Night Light pack of 1",
    price: "330.00",
    color: "Multi",
    badge: true,
    des: "Feature-this night light can use the usb or battery power supply it can control rotation and make lamp luminous or colorful light. So beautiful best gift for your kids they will be a good sleep at night for decorating wedding, birthday, parties. Great for romantic night lamp and decoration light use. Best for home, bedroom, children rooms. Very romantic night, full of sincere gift. Power by 4 x aaa battery not included or usb cable. Energy power saving and environmental friendly.",
  },
  {
    _id: 1011,
    img: spfTwo,
    productName: "Jaiman Toys LEGO Technic Ferrari Daytona Sp3 42143 Building Kit (3,778 Pieces), Multi Color",
    price: "48990.00",
    color: "Mixed",
    badge: true,
    des: "From the LEGO Technic Ultimate Car Concept series-The 4th addition to this series of supercar builds: a range of collectible models inspired by some of the world's most luxurious vehiclesDesigned in collaboration with Ferrari-Features include steering, a V12 engine, an 8-speed sequential gearbox with paddle shift, opening butterfly doors, a removable roof and shock absorbers A car gift for Ferrari fans -This buildable supercar model is designed for adult LEGO builders and Ferrari fans, offering a detailed building project with a display piece to admire Made for display -Includes a decorated display plate and a unique serial number to unlock special online rewards and content.",
  },
  {
    _id: 1012,
    img: spfThree,
    productName: "Rubela Kitchen Set Cooking Toy with Briefcase and Accessories, 26 PCS. Kitchen Playing Set",
    price: "399.00",
    color: "Mixed",
    badge: false,
    des: "Rubela Presents Kitchen Set is all that the children need to cook in their own Pretend Play Kitchen Set. This Play Set gets the kids to involve themselves in playful activities that are highly beneficial to them and also Super Fun. It is the best Cooking Companion for all-day fun play. Children can pretend cooking with utensils which encourages their fine motor skills, role-playing, imaginative play and introduces the kids to daily household kitchen chores. Best Cooking Pretend Play Set for Active Role-Play and Super Fun-Filled Hours. This is the ultimate gift for every little boy or girl! Great for birthdays, name days and Christmas gift-giving, it will surely put an ear-to-ear smile on your kid’s face.",
  },
  {
    _id: 1013,
    img: spfFour,
    productName: "Zyamalox Little Toys Multicolor Plastic Electric Water Circulation with Music Light Go Fishing Game Board Play Set Toy - Pack of 21",
    price: "1299.00",
    color: "Mixed",
    badge: false,
    des: "Promotes hand and eye coordination. Creates a fun and interactive fishing experience for child. Add water to fishing board and activate the buttons, water will go into circular motion. Accompanied music and lighting. Water scoop for fishing. Fishing rod rotates 360 degrees. Promotes bonding time with child when playing in 2 persons mode. Beautiful waterproof stickers. Multiple accessories.",
  },

  {
    _id: 1014,
    img: image14,
    productName: "V. B. K Hand Mittens With Cap (Pack Of 15)",
    price: "397.00",
    color: "Multi",
    badge: true,
    des: "V.B.K Hand Mittens With Cap (Pack Of 15",
  },
  {
    _id: 1015,
    img: image15,
    productName: "SMARTOTS Combo Pack of 2 Kids Shoes with Light and Velcro-C.Green/Pink",
    price: "499.00",
    color: "Mixed",
    badge: false,
    des: "Elevate your style with these Classy Pair of Kids Casual Shoes from the House of SMARTOTS brand. Featuring a Contemporary Refined Design with exceptional comfort, these pair are perfect to give your quintessential dressing an upgrade.These Stylish Casual Kids Shoes is a perfect choice for your little one. Attractive design and vibrant shade of this pair, makes it a must-have for your kids. Can be used as Casual daily use.An Ideal Pick for Kids casual footwear, the kids shoes will provide your feet with maximum flexibility and comfort and will also be highly durable, owing to their High Quality Upper and lining. Designed as per the latest trend, this pair will catch every Kid's attention. An all-weather staple, this pair can be teamed with your varied outfits. This shoes offers out of the box comfort for your all day activities. This casual shoes features light weight for enhanced natural walking motion. Go from outdoor adventure to indoor dining in these stylish shoes. This is an Excellent Pair of Shoes with Best Quality at the Best price.",
  },
  {
    _id: 1016,
    img: image16,
    productName: "Kats Baby Casual Musical CHU CHU Sound Slipon Kids Shoes (9 Months to 24 Months)",
    price: "250.00",
    color: "white",
    badge: true,
    des: "This stylish Pair of Shoe is a perfect choice for your little one. Attractive design and vibrant shade of this pair, makes it a must-have for your kids. Can be used as Party Wear, Sports & Casual. Upper made of high quality Material. Paired with a beautiful outfit, the Shoe are sure to garner attention. KATS Lifestyle causal Sandal-Soft and cozy lining keeps your feet to be hugged and comfortable for all day. Perfect match for your various shirt, is fashion and charming. It is flexible and anti-slip out sole, perfect for daily wear and fit different occasions, such as party, vocation, daily and so on",
  },
  {
    _id: 1017,
    img: image17,
    productName: "The Moms Co. Natural Diaper Rash Cream 25gm",
    price: "120.00",
    // color: "Black",
    badge: false,
    des: "The Moms Co. Diaper Rash Cream helps Prevent, Treat and Soothe diaper rashes & skin inflammation with USDA-Certified Organic Actives including 15% Zinc Oxide, Hydrolized Oat Protein & Organic Chamomile Oil. Specially designed for Baby's first 3 years, it is safe and gentle for all little ones.Direction For Use Step 1: Take a small amount of Diaper Rash Cream on your fingers. Step 2: Create a thin layer of the cream on the affected area. Step 3: For best results, apply the cream after every diaper change.",
  },
  {
    _id: 1018,
    img: image18,
    productName: "Himalaya Total Care Baby Pants Diapers-L 76'S",
    price: "₹1275.00",
    // color: "Black",
    badge: true,
    // des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1019,
    img: image19,
    productName: "Junior Kid Green 16 Inches With Training Wheels Cycle",
    price: "3193.00",
    color: "Red",
    badge: true,
    des: "Bring home Junior Kid cycles, that are easy to install as they come 90 percent assembled. Whether you are looking for a bicycle to meet your fitness goals or to surprise your little one, having the right bike will make a lot of difference. They come in different colors and sizes so as to suit your needs, with features like, MTB tires, robust frame and comfortable saddle. With more than 50 products, available, it is no wonder that millions of customers continue to choose Junior Kid ! Junior Kid has been strongly trusted by loyal consumers for over 15 years. Made for you, and made especially for your fitness .We wish a very happy riding.",
  },
  {
    _id: 1020,
    img: image20,
    productName: "Urban Terrain Cycle MTB Bolt 26T Single Speed, Front & Rear Disc Break, Front Suspension UT5000S26 Green",
    price: "5949.00",
    color: "Green",
    badge: true,
    des: "The Urban Terrain Cycle is a cutting-edge and versatile bicycle specifically designed for navigating the dynamic landscapes of urban environments. With a sleek and modern design, this cycle seamlessly blends style and functionality to cater to the demands of city living. So what are you waiting for? Go ahead and buy this product online today! Disclaimer: Despite our attempts to provide you with the most accurate information possible, the actual packaging and color of the product may sometimes vary. Please read the label, directions, and warnings carefully before use.",
  },
  {
    _id: 1021,
    img: image21,
    productName: "Brand Gadget ASWORLD Blue Bluetooth Headset for Kids",
    price: "1220.00",
    color: "Blue",
    badge: true,
    des: "Specification- Listening time- 8 hours Bluetooth receiving distance- 10 meters Charging time- 1.2 hours Bluetooth chip- Bluetooth version 5.0 Standby time- 148 hours Speaker specification- 40mm Use mode- Bluetooth or card or aux Charging box battery capacity- 400mah Headphone size- 9x17x20cm Packing List- 1 Bluetooth cat headphones, 1 Aux and 1 USB cable",
  },
  {
    _id: 1022,
    img: image22,
    productName: "Instabuyz Zipper Large Capacity Pencil Pouch Pencil Box Color Pouch for Kids, School, College & Office",
    price: "399.00    ",
    // color: "Black",
    badge: true,
    des: "Manage your stationery items with this pouch stationary pouches are a fun way to store kids belongings.This set is perfect for home, school and college. Organize the pencils, pens, erasers, Brushes, rulers, sharpeners and other stationery accessories in it in a safe way. The zippered pouch is very convenient in use and easy to carry as well. It is very light in weight and easily fits in your backpack without any hassle. Great for students, artists, writers, designers, Travelers and more. Zip Closer Compact size, easy to carry and convenient for use Pouch Size - Length-22cms , Height-8cms , Width-6 cms Easy storage and cleaning as is lightweight. Use: Desk, Type: Storage Bags, Product: pencil case Multifunctional Large Capaciy Bag, Can hold pen, pencil, makeup brushes, eraser, rule, notes or other small gadgets, etc",
  },
  {
    _id: 1023,
    img: image23,
    productName: "Myhoodwink Ride-on Ferrari Magic Car| Kids Push Car| Swing Car | Comfortable Seats | Elegant Design | Ride on Toy Car for Kids|Twister Ride on|Magic Toy Car|Kids Ride On| Push Rider| Steering Music & Lights For Kids",
    price: "996.00",
    // color: "Blank and White",
    badge: true,
    des: "Material: Plastic Type: Electronic Pets Battery Required: No Recommended Age: 2-4 Years Battery Available: No Net Quantity (N): 1 Little funky brings unbreakable plastic made of high quality virgin material. Kids will have unlimited fun while playing with this Magic Car Rider Magic Baby racing car for kids with music and lights. Kids will roam in the house with music and lightning effect. 360 degree easy Revolvement of ride on car works on mechanical power without much effort. Wonderful work of science. No batteries or paddling required to move the car just move the handle and the car will move. Recommended Age: 2 To 8 Years Strongest among all - Made with high quality plastic with high strength that it can bear load of adults too. Smooth and Fast Ride â€“ Used ABEC 7 Bearing for Fast Ride and Ultra Smooth Experience while ridin",
  },
  {
    _id: 1024,
    img: image24,
    productName: "SaleOn Big Size Set of 2 Unbreakable Trucks Friction Powered Cars for Kids Rock Truck Toddler for boys gifts for Toddler Truck Diecast Inertial Off-Road Four-Wheel Drive Simulation Stunt Swing Car Toy - Multicolor",
    price: "279.00",
    color: "Multi",
    badge: true,
    des: "Inertial motion, easy to operate, just need gently push forward, the wheel will drive along with the inertia motion. Shockproof vehicle wheels design, make it able to drive on rough road. Reduce the shake during driving. Exercising the flexibility and capacity of hands and eyes, encouraging kid's imagination , This car boasts extraordinary grip. It is designed with an anti-collision head, being capable of driving stably in all terrains like beach, sand, grass or concrete road, etc..",
  },
  {
    _id: 1025,
    img: image25,
    productName: "Buddsbuddy Premium Wide Neck Feeding Bottle - Pink 150 ml",
    price: "225.00",
    color: "Pink",
    badge: true,
    des: "Buddsbuddy is a trusted name in Baby Care. The products are a result of defined purpose of utility, thoughtful innovation, thorough research, environmental consciousness and devotion to creating products that are safe, effective, accessible and sustainable. Special care is taken while making the products and quality standards are strictly followed. The designs are kid-friendly and functional. The products are non-toxic, clinically tested and approved by FDA & CE. The FDA & CE approved products are a guarantee that the customer has the best of the products that have passed international standards of healthcare and medicine",
  },
  {
    _id: 1026,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1027,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1028,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1029,
    img: bestSellerTwo,
    productName: "New Backpack",
    price: "180.00",
    color: "Gray",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1030,
    img: bestSellerThree,
    productName: "Household materials",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1031,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1032,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1033,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1034,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1035,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1036,
    img: newArrTwo,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1037,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1038,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1039,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1040,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1041,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1042,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1043,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1044,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1045,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1046,
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
// =================== PaginationItems End here =================
